markdown: kramdown


url: ""

baseurl:


title: Gergő & Zsófi Esküvő

description: "Egy szív: fél szárny. Most már repülhetsz."
description2: ~ Illyés Gyula ~

site-image: assets/images/logo.png

favicon-url: assets/images/logo.png


heroimage: ../../assets/images/hero.jpeg

email: /
facebook_username: /


author-name: Niarit

author-about2: Proin imperdiet rutrum rutrum. Maecenas vitae enim nunc. Quisque eu nunc at odio lacinia sodales at eget lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In venenatis sapien a odio cursus egestas. Curabitur a nunc quis urna finibus aliquam. Nunc molestie scelerisque volutpat. Sed pharetra nisl quis efficitur maximus. Quisque id diam in sapien auctor euismod vulputate et ligula. Vestibulum in malesuada magna.

author-url: /

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  - scope:
      type: "posts"
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  - scope:
      type: "pages"
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
