markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Gergő & Zsófi Esküvő
# Description of the Site
description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
# URL of Image of the Site
site-image: assets/images/logo.png
# URL for the Image of custom Favicon
favicon-url: assets/images/logo.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: ../../assets/images/hero.jpeg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: /
facebook_username: /


# Name of the Author
author-name: Niarit
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis tempus eget justo sed euismod. Curabitur suscipit, erat sed efficitur consectetur, augue sem posuere magna, nec lacinia tortor ipsum quis dolor. Integer leo ex, interdum vel erat quis, tincidunt vehicula eros. Aenean imperdiet tincidunt sem, vel fermentum velit ullamcorper a. Suspendisse non ligula eros.
author-about2: Proin imperdiet rutrum rutrum. Maecenas vitae enim nunc. Quisque eu nunc at odio lacinia sodales at eget lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In venenatis sapien a odio cursus egestas. Curabitur a nunc quis urna finibus aliquam. Nunc molestie scelerisque volutpat. Sed pharetra nisl quis efficitur maximus. Quisque id diam in sapien auctor euismod vulputate et ligula. Vestibulum in malesuada magna.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: /

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
